<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="PAVULURU" failures="1" tests="5" name="Peronal loan" time="0.48" errors="0" timestamp="2021-06-23T16:24:35 GMT-04:00">
  <testcase classname="test.Basic2" name="ploan" time="0.014"/>
  <testcase classname="test.Basic1" name="Demo" time="0.027">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Basic1.Demo(Basic1.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Basic4" name="LoginApiHomeLogin" time="0.004"/>
  <testcase classname="test.Basic4" name="MobileLoginHomeLoan" time="0.006"/>
  <testcase classname="test.Basic4" name="webloginHomeLoan" time="0.004"/>
  <testcase classname="test.Basic1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Peronal loan -->
